//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataFirstCRUDIslemleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmBilgisi
    {
        public int FilmId { get; set; }
        public string FilmAdı { get; set; }
        public int FilmSeansId { get; set; }
        public int UcretId { get; set; }
    
        public virtual SeansBilgisi SeansBilgisi { get; set; }
        public virtual Ucret Ucret { get; set; }
    }
}
